- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
  become: true

- name: Restart dnsmasq
  ansible.builtin.systemd_service:
    name: "{{ dnsmasq_service_name }}"
    state: restarted
  become: true
